version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest

  build:
    command: echo "Building the file"
      go build main.go

  post_build:
    command: echo "Running tests"
      go test ./... -v

artifacts:
  files: main
