version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest

  build:
    commands:
      - ls -la
      - echo "Building the file"
      - go build main.go

  post_build:
    commands:
      - echo "Running tests"
      - go test ./... -v

artifacts:
  files:
    - main
    - test.sh
    - runapp.sh
